name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  # workflow_run:
  #   workflows: [Test]
  #   types: [completed]
  #   branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          check-latest: true
          node-version-file: .node-version
      - run: npm ci
      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: data
          key: ${{ runner.os }}-finance-data
      - run: npm run sync-coinbase
      - uses: actions/cache/save@v3
        with:
          path: data
          key: ${{ steps.cache.outputs.cache-primary-key }}
      - run: npm run build-coinbase
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: 'www'
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
