name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Tests, Schedule]
    types: [completed]
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
env:
  TZ: UTC
  LANG: en_US.UTF-8
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: data
          key: jsonl-data
      - run: npm run sync-coinbase
      - uses: actions/cache/save@v4
        with:
          path: data
          key: ${{ steps.cache.outputs.cache-primary-key }}
      - run: npm run build-coinbase-intervals
      - run: npm run build-coinbase
      - run: npm run build-coinbase-shallow
      - run: npm run build-coinbase-history
      - run: npm run build-sitemap
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: 'www'
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
